### PR TITLE
Pull Request for #121: Changed country names in variable "countryData" 

### PR DESCRIPTION
**Pull request by 55abhilash**
Changed country names in variable "countryData" according to names on worldometer so that getCountryData returns properly.

### CODE REVIEW

**Comment by buster95** [comment]
I add synonyms or possibles names, this PR isn't necessary, was resolve on #117

**Comment by 55abhilash** [comment]
But the synonyms or possible names are not included in array "countryData". They are in a different array, which is not being accessed in "getCountryData". 
If your synonyms are to be used, kindly change the code in function "getCountryData" accordingly.

**Comment by buster95** [comment]
Idea is synonyms just for searches getCountryData only return standardized country name

**Comment by EliteDaMyth** [comment]
Does this have to be merged

**Comment by 55abhilash** [comment]
@buster95 : This is the first few lines of code of function getCountryData : 
`const getCountryData = function (countryName) {
    for (const index in countryData) {
        if (**countryData[index].country.toLowerCase() == countryName.toLowerCase()**) {
            const data = countryData[index]`
Notice the comparison in **if**.

And this is called in getCountries.js line 54:
`            let country =
                cell.children[0].data ||
                cell.children[0].children[0].data ||
                // country name with link has another level
                cell.children[0].children[0].children[0].data ||
                cell.children[0].children[0].children[0].children[0].data || "";
result.push({ country, countryInfo: countryUtils.getCountryData(**country**) });`
Here, the variable **country** is coming from worldometer html table. Value of this variable is compared to **countryData** value as discussed above. 
Hence, if you use standardized names in countryData, and not names similar to worldometer html table, the comparison in **if** will fail, and it will:
`return { iso2: 'NO DATA', iso3: 'NO DATA', _id: 'NO DATA', lat: 0, long: 0, flag:`

I hope this explanation is verbose enough :P

**Comment by buster95** [comment]
ok 
`{ country: 'United States', iso2: 'US', iso3: 'USA', _id: 840, lat: 38, long: -97, possibleNames: ['USA', 'Estados Unidos'] },`

you can look for `USA`, `Estados Unidos` or `United States`
ex.
**`countries/usa`**
**`countries/estados%20unidos`**
**`countries/united%20states`**

all urls response with the same data, displayed country name will be **`United States`** because is on country field.

you can do unit tests for `getCountryData` function to understand how it work

**Comment by 55abhilash** [comment]
Problem is not while doing **/countries/usa**, it is during **/countries**. Country name in such case is United States and worldometer names is USA. That's the mismatch.
I can show you the error on discord. Is it possible?

**Comment by EliteDaMyth** [comment]
we standardise the country name. the names are not the same as worldometers

**Comment by 55abhilash** [comment]
Ok. In that case, `{ if (countryData[index].country.toLowerCase() == countryName.toLowerCase())`
this should compare countryName (From WorldoMeter) to isoCountries array, which contains all possible country names and synonyms by @buster95 instead of countryData, which contain only standardised names. In this way, we standardise the country names, and data is also fetched for countries with non standard names on worldometer.

**Pull request closed without merging**
