### PR TITLE
Added C# wrapper(Covid19Tracker.NET)

### PR DESCRIPTION
**Pull request by egbakou**
Hi,
Thanks for this API.

I added another C# wrapper for the API, and the nuget package is already available here https://www.nuget.org/packages/Covid19Tracker.NET/.
This wrapper contains methods that return objects, which can be easily handled in applications. The await/async best practices are also used.

### CODE REVIEW

**Comment by puf17640** [comment]
Looks cool!

**Comment by egbakou** [comment]
Okay @puf17640

**Comment by egbakou** [comment]
> 
> 
> Okay @puf17640

Added !

**Comment by egbakou** [comment]
> 
> 
> Looks cool! Please add it to our [awesome-list](https://github.com/novelcovid/awesome-novelcovid)

Added to [awesome-list](https://github.com/novelcovid/awesome-novelcovid)

**Pull request closed without merging**
