### PR TITLE
[Code Improvements]

### PR DESCRIPTION
**Pull request by buster95**
[Hot Reload Server] Nodemon Server for Developers
-  command: npm run start:dev

[historical searches] Some others issues found

### CODE REVIEW

**Comment by ebwinters** [comment]
will check this out in a bit 👍

**Comment by ebwinters** [comment]
what is the purpose of running nodemon in production @buster95 we already have webhook

**Comment by buster95** [comment]
> what is the purpose of running nodemon in production @buster95 we already have webhook

not @ebwinters  nodemon for dev enviroment not for production, I'm tired of restarting the local server every time I make a change

**Comment by ebwinters** [comment]
Got it good idea.

**Pull request merged**
