### PR TITLE
getYesterday's statistics.

### PR DESCRIPTION
**Pull request by Mr-Cerberus**
I don't know if it is something people will use but it's nice to add I guess.

Possibly could do with a bit more editing so it doesn't look like `getCountries.js`

### CODE REVIEW

**Comment by ebwinters** [comment]
What does this even do? It's just unused code that isn't called anywhere

**Comment by Mr-Cerberus** [comment]
It pulls the statistics from the yesterdays values, similar to historical statistics except it pulls only yesterdays values. 

Example
```json
 {
    "country": "China",
    "cases": 81171,
    "yesterdayCases": 78,
    "deaths": 3277,
    "yesterdayDeaths": 7,
    "recovered": 73159,
    "active": 4735,
    "critical": 1573,
    "casesPerOneMillion": 56,
    "deathsPerOneMillion": 2
  }
```
Todays:
```json
{
    "country": "China",
    "cases": 81218,
    "todayCases": 47,
    "deaths": 3281,
    "todayDeaths": 4,
    "recovered": 73650,
    "active": 4287,
    "critical": 1399,
    "casesPerOneMillion": 56,
    "deathsPerOneMillion": 2
  }
```

**Comment by Krato** [comment]
This will be great to do some calculations.

**Comment by Mr-Cerberus** [comment]
@Krato using this you would be able to do some percentages like this:
```js
result.increaseCases = `${((result.cases - result.ytotalCases)/result.cases * 100).toFixed(2)}%`;
 result.increaseDeaths = `${((result.deaths - result.ytotalDeaths)/result.deaths * 100).toFixed(2)}%`;
 result.increaseRecovered = `${((result.recovered - result.ytotalRecovereds)/result.recovered * 100).toFixed(2)}%`;
 result.increaseActive = `${((result.activeCases - result.yactiveCase)/result.activeCase * 100).toFixed(2)}%`;
 result.increaseCritical = `${((result.criticalCase - result.ycriticalCase)/result.criticalCase * 100).toFixed(2)}%`;
```

**Comment by ebwinters** [comment]
The code is not integrated anywhere though like there is no endpoint you're submitting a function that isn't being used anywhere

**Comment by Mr-Cerberus** [comment]
@ebwinters I can easily merge an integration if needs be.

**Comment by Mr-Cerberus** [comment]
```js
app.get("/countries/:country/yesterday", async function (req, res) {
  let countries = JSON.parse(await redis.get(keys.yesterday))
  const standardizedCountryName = countryMap.standardizeCountryName(req.params.country.toLowerCase());
  let country = countries.find(e => {
    // see if strict was even a parameter
    if (req.query.strict) {
      return req.query.strict.toLowerCase() == 'true' ? e.country.toLowerCase() === standardizedCountryName : e.country.toLowerCase().includes(standardizedCountryName)
    }
    else {
      return e.country.toLowerCase().includes(standardizedCountryName);
    }
  });
  if (!country) {
    res.send("Country not found");
    return;
  }
  res.send(country);
});
```
Simple to add the endpoint ¯\_(ツ)_/¯

**Comment by ebwinters** [comment]
Alright then it looks fine if we want to use the function to integrate later to v2/countries, could be useful to have

**Comment by EliteDaMyth** [comment]
Not being used yet but will be in future. Merging for now

**Pull request merged**
