### PR TITLE
Refactoring renameKeys

### PR DESCRIPTION
**Pull request by jsebastianms1**
Hello! after @puf17640 comment, to refactor this method i did it, please tell me what you think.
 
I have a question with the translations, do i have to add these to a locales folder, or config/locales, what do you recommend me to do? thanks in advance

### CODE REVIEW

**Comment by ebwinters** [comment]
@puf17640 and I will review by tomorrow

**Comment by jsebastianms1** [comment]
> To be honest I've looked at the code for like 15 minutes and can't figure out what's going on. I think just leave it the way it was, and try to refactor `getInfo`
> It's extremely confusing as of right now... should at least have JSDoc

I will close this PR and try to refactor getInfo, adding a JSDoc also, thanks for your comment

**Comment by ebwinters** [comment]
Yes. I mean it in the nicest way possible lol

**Comment by puf17640** [comment]
Sorry for not reviewing, I am currently really busy myself. 
Thanks for taking the time though, I really appreciate it! As said, I will have my own shot at refactoring it in the next weeks, let's see if my outcome is a bit more understandable. 👍

**Pull request closed without merging**
