### PR TITLE
Adding novelcovid-scraper library to Readme

### PR DESCRIPTION
**Pull request by skavinvarnan**
### This package is a fork from our repo
Our whole source code will run as a library

### Github and NPM Package URL

**Github - https://github.com/COVID19-SARS-CoV-2/covid19-scraper**
**NPM Package - https://www.npmjs.com/package/novelcovid-scraper**

### Instructions
Instruction on getting started can be found here https://www.npmjs.com/package/novelcovid-scraper#getting-started

### Updates
Once in 3 days changes from our main repo will be pulled, and an update will be published.

### CODE REVIEW

**Comment by ebwinters** [comment]
I’m confused. If your package uses our API, see our showcase repo: https://github.com/NovelCOVID/awesome-novelcovid. Otherwise, why would we add your package to our readme, we have our own package with over a million downloads.

**Comment by skavinvarnan** [comment]
There is a difference. Your official package ```novelcovid``` internally makes API requests to ```https://disease.sh/v2``` you can find it here https://github.com/NovelCOVID/node-api/blob/master/src/index.ts#L11

But the package ```novelcovid-scraper``` i have done it basically runs on the entire source on the end users machine, so the scraping is done on the local machine and redis is updated. Checkout the guide [here](https://www.npmjs.com/package/novelcovid-scraper#start-server) and code [here](https://github.com/COVID19-SARS-CoV-2/covid19-scraper/blob/master/start.js#L37)

This package is very similarly to the [docker-compose run](https://github.com/NovelCOVID/API#run-with-docker-compose) with three differences
1. Runs along with your NodeJS project
2. API server doesn't start
3. Only the scraper starts and updates redis, based on the config provided [here](https://www.npmjs.com/package/novelcovid-scraper#set-config)

So that is why i have added it to readme under Run with docker-compose

This package was very useful for me to build a the API's based on graphql. Take a look at this https://github.com/COVID19-SARS-CoV-2/web-covid-api#apis

**Comment by skavinvarnan** [comment]
Updated readme to give move clarity

**Comment by ebwinters** [comment]
Today we are merging docker support where we have split the scraping job from the API serving job. You can check it out on branch `docker-dev`. Otherwise, please add this to our `awesome-novelcovid` repo I mentioned above. Thanks for your time!

**Comment by skavinvarnan** [comment]
Sure will do thanks.

**Pull request closed without merging**
