### PR TITLE
Daily Cases for Global historical data, GET /v2/historical/all

### PR DESCRIPTION
**Pull request by buster95**
Working...

### CODE REVIEW

**Comment by puf17640** [comment]
what about dailyDeaths and dailyRecovered ? also, should we really do this? @ebwinters

**Comment by ebwinters** [comment]
yeah I don't really know about this, as it isn't data directly provided by he source and there's no real need

**Comment by buster95** [comment]
I was making this because, I'd like to add a graph to see the infection curve, something like this
image

**Comment by buster95** [comment]
> what about dailyDeaths and dailyRecovered ? also, should we really do this? @ebwinters

eventually I could add dailyDeaths and dailyRecovered

**Comment by puf17640** [comment]
yeah but the point is we shouldnt really add to much to it that isnt provided in the first place to keep it more an official thing, for the countries endpoints I did it because worldometers was already providing a few of the "perOneMillion" values and so it was pretty much implied to have those as well for the other values (even more after we got population value per country)

**Comment by buster95** [comment]
data is provided only subtracts the day from the day before, if you check other data is the same thing

**Comment by GliderCodes** [comment]
something I'm currently using to get the daily data
```typescript
function getDaily(data) {
  Object.entries(data).map(async ([type, object]) => {
    let prevNum = 0;
    Object.entries(object).map(([date, value]) => {
      daily[type as keyof typeof data] = {
        ...daily[type as keyof typeof data],
        [date]: (value as number) - prevNum
      };
      prevNum = value as number;
    });
  });
  return daily;
}
```

**Comment by puf17640** [comment]
what is this type sorcery

**Comment by buster95** [comment]
> something I'm currently using to get the daily data
> 
> ```ts
> function getDaily(data) {
>   Object.entries(data).map(async ([type, object]) => {
>     let prevNum = 0;
>     Object.entries(object).map(([date, value]) => {
>       daily[type as keyof typeof data] = {
>         ...daily[type as keyof typeof data],
>         [date]: (value as number) - prevNum
>       };
>       prevNum = value as number;
>     });
>   });
>   return daily;
> }
> ```

In this PR I was working in that 😥, to incorporate daily cases, daily deaths and daily recovered

**Comment by puf17640** [comment]
i see, but me and ethan both agreed on trying to keep the motto "scrape and serve" without transforming the data too much, since most of the stuff can be done clientside anyway

**Pull request closed without merging**
