### PR TITLE
added sorting by parameter and option for asc/desc sort

### LINKED ISSUE #52: sorting by a param does not seem to work correctly
the titles explains it all. 
i tried ' https://corona.lmao.ninja/countries?sort=todayDeaths '
but the result is not sorted by the parameter provided.

### PR DESCRIPTION
**Pull request by pg07codes**
currently the option for sorting by parameter is not working. Fixes #52 
i have added it + the functionality to sort in ascending order (default is descending sort).
and yeah, great job making this API :+1:

### CODE REVIEW

**Comment by pg07codes** [comment]
@EliteDaMyth if you approve of the changes, i may update the readme file accordingly.

**Comment by EliteDaMyth** [comment]
have you tested? if its working fine i'll merge soon

**Comment by pg07codes** [comment]
yeah I've tested it .

**Comment by EliteDaMyth** [comment]
will merge when @dicedtomatoreal is online :)

**Comment by pg07codes** [comment]
why was it closed ? @EliteDaMyth @dicetomatoreal . changes were tested and approved by eliteDaMyth

**Comment by EliteDaMyth** [comment]
We decided this can be easily done on the client side so it's not necessary and wastes the servers computing power on each sort request.

**Pull request closed without merging**
