### PR TITLE
new header design, sticky, donate CTA style

### PR DESCRIPTION
**Pull request by ba1948**

### CODE REVIEW

**Comment by EliteDaMyth** [comment]
can you show a small demo of the thing?

**Comment by EliteDaMyth** [comment]
maybe a small video etc

**Comment by ba1948** [comment]
Demo video:
https://drive.google.com/file/d/1fNlcZwYGYkppOXan1H3Ti6PWHVAn0fm9/view

**Comment by EliteDaMyth** [comment]
Seems good!

**Comment by puf17640** [comment]
very nice work

**Pull request merged**
