### PR TITLE
[Feature][Improvements]

### LINKED ISSUE #196: No recovered data
Data for people who have recovered has been removed from version 2

### LINKED ISSUE #279: ISO-code search in historical endpoint
This is really great API! Thanks for developing it.

The `countries` endpoint now supports the ISO country codes in the search (#229 ). However, the v2 `historical` does not support the same. Would it be possible to add it, as ISO codes are sometimes easier to use?

### PR DESCRIPTION
**Pull request by buster95**
- [x] Historical data filtered by Country Id and ISOs standards
**`/v2/historical/{countryName}`**
**`/v2/historical/{countryId}`**
**`/v2/historical/{iso2}`**
**`/v2/historical/{iso3}`**
**`/v2/historical/{countryName}/{province}`**
**`/v2/historical/{countryId}/{province}`**
**`/v2/historical/{iso2}/{province}`**
**`/v2/historical/{iso3}/{province}`**
- [x] Code Improvements
- [x] historical data for recovered was added in this PR

closed #279 
closed #196

### CODE REVIEW

**Comment by ebwinters** [comment]
reviewing :)

**Comment by ebwinters** [comment]
Noting a bug where /v2/historical/countrName gets specific province data where provinces exist, like china

**Comment by ebwinters** [comment]
Noting bug where `getCountryData` returns null return data for input countryID

**Comment by buster95** [comment]
Ethan you are changing code, how I can know what happens if you change all the code

**Comment by ebwinters** [comment]
@buster95 I'm doing this all locally, while testing. Don't worry I will make sure everything works before merging.

**Comment by ebwinters** [comment]
@all-contributors please add @benjamin-sommer for code

**Comment by Nekiono** [comment]
Very clean PR. Kudos.

**Pull request merged**
