### PR TITLE
WIP: Add showcase

### PR DESCRIPTION
**Pull request by renanbastos93**
I want to propose a new area to showcases other apps that use this API

### CODE REVIEW

**Comment by ebwinters** [comment]
I like this idea a lot :)

**Comment by Nekiono** [comment]
This is a very nice idea, but won't merge just now; let's add a few more before kicking this off

**Comment by renanbastos93** [comment]
Okay, no worries.

Well, Do you have more cases to add in this pull request?

**Comment by Nekiono** [comment]
On our Discord server, we have an entire channel dedicated to showcasing. Maybe we could talk to some of the creators there :)

**Comment by renanbastos93** [comment]
> On our Discord server, we have an entire channel dedicated to showcasing. Maybe we could talk to some of the creators there :)

How nice, I liked. My speech is so so (more less). well, I will enter on Discord.

**Comment by Tetracyl** [comment]
Twitter Coronavirus Bot (Tweets statistics every 12 hours): https://github.com/Tetracyl/CoronaCord
Coronavirus Discord Bot with maps and statistics: https://github.com/Tetracyl/CoronaCord
Coronavirus App for Android and iOS (made with unity): https://github.com/Tetracyl/COVID19-App

If you need more details please ask me! Amazing API btw <3

**Comment by apex2504** [comment]
This sounds like a very interesting way for other creators to get their projects noticed.

With that being said, [here](https://github.com/apex2504/python-corona-api) is a wrapper for the API written in Python. We have complete or near-complete coverage of the API and its endpoints. You can install it through pypi `python3 -m pip install -U corona_api`.

Admittedly this isn't so much a project created using the API, but is more of a way to made the API more easily accessible for many people.

**Comment by WarenGonzaga** [comment]
Here's mine...

## COVID-19 Tracker CLI

Description: It is an open-source NodeJS application for command line interface to track COVID-19 cases around the world. An optimized NodeJS application and a simple tracker with real-time updates from NovelCOVID API.

Developed by Filipino Developers. **[Tracker CLI Developers](https://github.com/trackercli)**

Officially sponsored by **[Vercel](https://vercel.com/)**

Repo: https://github.com/trackercli/covid19-tracker-cli

**Comment by renanbastos93** [comment]
It was added your showcases. Do you have more suggestions?

**Comment by WarenGonzaga** [comment]
@renanbastos93 It would be better if you use ``Tracker CLI Developers`` instead of ``Filipino Developers`` thank you!

**Comment by kylerphillips** [comment]
Here’s my project if it helps :)

viruscovid.tech

**Comment by renanbastos93** [comment]
> @renanbastos93 It would be better if you use `Tracker CLI Developers` instead of `Filipino Developers` thank you!

Ok, I am sorry for my wrong

**Comment by renanbastos93** [comment]
> Here’s my project if it helps :)
> 
> viruscovid.tech
> 
> Source code on my GitHub repo

Please, send us the link.

**Comment by WarenGonzaga** [comment]
@renanbastos93 Its okay... great job by the way!

**Comment by renanbastos93** [comment]
> @renanbastos93 Its okay... great job by the way!

Thanks a lot

**Comment by drewpayment** [comment]
Here is an open source Angular 9 web application with Plotly and Highcharts implementation at: https://stopcovid.dev. 

https://github.com/drewpayment/covid-19

**Comment by jobayerarman** [comment]
Info dashboard for Bangladesh in local language(BD-BN) [https://covidbd.herokuapp.com/](https://covidbd.herokuapp.com/)

**Comment by puf17640** [comment]
## GUYS THANK YOU ALL FOR YOUR COMMENTS

We have made a list to showcase all projects, which can be found here: https://github.com/puf17640/awesome-novelcovid
## I WILL ADD ALL PROJECTS POSTED ABOVE THIS COMMENT MANUALLY
## IF YOU SEE THIS, PLEASE DO NOT POST UNDER THIS COMMENT, ADD YOUR PROJECT TO THE LIST

**Comment by renanbastos93** [comment]
> ## GUYS THANK YOU ALL FOR YOUR COMMENTS
> We have made a list to showcase all projects, which can be found here: https://github.com/puf17640/awesome-novelcovid
> 
> ## I WILL ADD ALL PROJECTS POSTED ABOVE THIS COMMENT MANUALLY
> ## IF YOU SEE THIS, PLEASE DO NOT POST UNDER THIS COMMENT, ADD YOUR PROJECT TO THE LIST

@puf17640 
Can we change this commit to add a link in this readme to project about showcases?

**Comment by puf17640** [comment]
yes please do so! 👍

**Comment by puf17640** [comment]
im on mobile so i cant change the readme and check if it looks good, but i can merge from here

**Pull request merged**
