### PR TITLE
Added CONTRIBUTION guideline

### PR DESCRIPTION
**Pull request by egbakou**
closes https://github.com/NovelCOVID/API/issues/698

### CODE REVIEW

**Comment by puf17640** [comment]
Thank you!

**Comment by EliteDaMyth** [comment]
Looks good will merge as soon as tests pass :)

**Comment by egbakou** [comment]
> 
> 
> Thank you!

You're welcome.
Thank you too !

**Comment by egbakou** [comment]
> 
> 
> Looks good will merge as soon as tests pass :)

Nice !

**Comment by EliteDaMyth** [comment]
@all-contributors please add @egbakou for docs

**Pull request merged**
