### PR TITLE
feat(kind): added kubernetes manifests and instructions

### PR DESCRIPTION
**Pull request by lukibahr**
* added instructions for kind (kubernetes in docker) setup
* added manifests for a kubernetes deployment of redis
* added manifests for a kubernetes deployment of the api
* fixed documentation

### CODE REVIEW

**Comment by EliteDaMyth** [comment]
how is it helpful though?

**Comment by lukibahr** [comment]
For running the app in a kubernetes environment. Helpful for serving the app in high-available setups for advanced scaling

**Comment by puf17640** [comment]
we are not using kubernetes to run the API, if we ever need scaling, this would be done using nginx

i still really appreciate the work you have done! have you tried it out also, does it run? how many instances have tried to run?

**Comment by lukibahr** [comment]
tried 2-3 replicas for the api, but havent had the time to run ha-redis setup.

**Comment by puf17640** [comment]
> tried 2-3 replicas for the api, but havent had the time to run ha-redis setup.

The question is, is there a distinct performance increase or other drastic benefits to nginx?

**Comment by lukibahr** [comment]
The performance might be the same, but the major benefit is the autoscaling behaviour and self-healing pattern that kubernetes comes with. How do you scale your apps and services behind your nginx?

**Comment by puf17640** [comment]
@lukibahr you would have to talk to @Nekiono because she is in charge of maintaining the server. she is also from germany. it should be just a default nginx config and the express backend behind it

**Comment by lukibahr** [comment]
Okay, i‘ll talk to her via discord. Let’s keep the branch and mr open till a decision is made

**Comment by ebwinters** [comment]
I don't think we want to use kubernetes, at least not yet. We are looking into a microservices infrastructure which could maybe use it in the future. I will close PR and mark it for later so we can get to it again if needed. Thanks for your work

**Pull request closed without merging**
